In [1]:
import pandas as pd
import numpy as np

In [198]:
df_joinable_columns['ds_name'].unique()

array(['road-ahead-current-road-closures.csv', 'eo_pr.csv', 'eo4.csv',
       'cultural-spaces.csv', 'street-intersections.csv',
       'rental-standards-current-issues.csv', 'public-art.csv',
       'schools.csv', 'community-gardens-and-food-trees.csv',
       'libraries.csv', 'community-centres.csv',
       'population-census-of-botswana-2011.csv',
       'statewise-census-data-in-india-1901-2011.csv',
       'public-art-artists.csv', 'eo_xx.csv'], dtype=object)

In [207]:
all_joinable_columns = np.concatenate((df_joinable_columns['ds_name'], df_joinable_columns['ds_name_2']), axis=0)
all_joinable_columns = np.unique(all_joinable_columns)
all_joinable_columns

array(['community-centres.csv', 'community-gardens-and-food-trees.csv',
       'cultural-spaces.csv', 'currency_exchange.csv', 'eo4.csv',
       'eo_pr.csv', 'eo_xx.csv', 'libraries.csv',
       'population-census-of-botswana-2011.csv', 'public-art-artists.csv',
       'public-art.csv', 'rental-standards-current-issues.csv',
       'road-ahead-current-road-closures.csv',
       'road-ahead-upcoming-projects.csv', 'schools.csv',
       'statewise-census-data-in-india-1901-2011.csv',
       'street-intersections.csv'], dtype=object)

In [2]:
df_joinable_columns = pd.read_csv('joinable_columns.csv')
df_joinable_columns.head()

,ds_name,att_name,ds_name_2,att_name_2
0,road-ahead-current-road-closures.csv,COMP_DATE,road-ahead-upcoming-projects.csv,COMP_DATE
1,eo_pr.csv,NTEE_CD,eo_xx.csv,NTEE_CD
2,eo_pr.csv,NAME,eo4.csv,NAME
3,eo_pr.csv,ICO,eo4.csv,ICO
4,eo_pr.csv,STREET,eo4.csv,STREET

In [3]:
df_joinable_columns.iloc[10:20,:]

,ds_name,att_name,ds_name_2,att_name_2
10,eo4.csv,NTEE_CD,eo_pr.csv,NTEE_CD
11,eo_pr.csv,SORT_NAME,eo4.csv,SORT_NAME
12,cultural-spaces.csv,LOCAL_AREA,street-intersections.csv,Geo Local Area
13,street-intersections.csv,Geo Local Area,cultural-spaces.csv,LOCAL_AREA
14,cultural-spaces.csv,LOCAL_AREA,rental-standards-current-issues.csv,Geo Local Area
15,rental-standards-current-issues.csv,Geo Local Area,cultural-spaces.csv,LOCAL_AREA
16,cultural-spaces.csv,LOCAL_AREA,public-art.csv,Neighbourhood
17,public-art.csv,Neighbourhood,cultural-spaces.csv,LOCAL_AREA
18,cultural-spaces.csv,LOCAL_AREA,public-art.csv,GeoLocalArea
19,public-art.csv,GeoLocalArea,cultural-spaces.csv,LOCAL_AREA

In [4]:
df_joinable_columns[df_joinable_columns['ds_name']=='cultural-spaces.csv']

,ds_name,att_name,ds_name_2,att_name_2
12,cultural-spaces.csv,LOCAL_AREA,street-intersections.csv,Geo Local Area
14,cultural-spaces.csv,LOCAL_AREA,rental-standards-current-issues.csv,Geo Local Area
16,cultural-spaces.csv,LOCAL_AREA,public-art.csv,Neighbourhood
18,cultural-spaces.csv,LOCAL_AREA,public-art.csv,GeoLocalArea
20,cultural-spaces.csv,LOCAL_AREA,schools.csv,Geo Local Area
22,cultural-spaces.csv,LOCAL_AREA,community-gardens-and-food-trees.csv,Geo Local Area
24,cultural-spaces.csv,ACTIVE_SPACE,community-gardens-and-food-trees.csv,NUMBER_OF_FOOD_TREES
25,cultural-spaces.csv,ACTIVE_SPACE,community-gardens-and-food-trees.csv,FOOD_TREE_VARIETIES
26,cultural-spaces.csv,LOCAL_AREA,libraries.csv,Geo Local Area
28,cultural-spaces.csv,LOCAL_AREA,community-centres.csv,Geo Local Area

In [5]:
df_dsInformation = pd.read_csv('datasetInformation_testbedXS.csv')
df_dsInformation.head()

,filename,delimiter,multiline,file,nullVal,file_size,ignoreTrailing,source
0,survey_results_schema.csv,",",True,csv,"""""",23kb,True,https://www.kaggle.com/stackoverflow/so-survey...
1,datasets_517172_952401_train.csv,",",False,csv,"""""",55kb,True,https://www.kaggle.com/sovitrath/diabetic-reti...
2,ability_ids.csv,",",False,csv,"""""",19kb,True,https://www.kaggle.com/devinanzelmo/dota-2-mat...
3,public-art.csv,;,True,csv,"""""",669kb,True,https://opendata.vancouver.ca/explore/dataset/...
4,public-art-artists.csv,;,True,csv,"""""",243kb,True,https://opendata.vancouver.ca/explore/dataset/...

In [6]:
files = df_joinable_columns['ds_name'].unique()
files

array(['road-ahead-current-road-closures.csv', 'eo_pr.csv', 'eo4.csv',
       'cultural-spaces.csv', 'street-intersections.csv',
       'rental-standards-current-issues.csv', 'public-art.csv',
       'schools.csv', 'community-gardens-and-food-trees.csv',
       'libraries.csv', 'community-centres.csv',
       'population-census-of-botswana-2011.csv',
       'statewise-census-data-in-india-1901-2011.csv',
       'public-art-artists.csv', 'eo_xx.csv'], dtype=object)

In [7]:
df_left = pd.read_csv('datasets/public-art.csv', delimiter=';')
df_left.head()

,RegistryID,ArtistProjectStatement,Type,Status,SiteName,SiteAddress,PrimaryMaterial,URL,PhotoURL,Ownership,Neighbourhood,LocationOnsite,Geom,GeoLocalArea,DescriptionOfwork,Artists,PhotoCredits,YearOfInstallation,Unnamed: 18
0,27,"""McHaffie says she means to show movement, but...",Sculpture,In place,Devonian Harbour Park,Denman & Georgia Street,"Stainless steel, cedar",https://covapp.vancouver.ca/PublicArtRegistry/...,https://opendata.vancouver.ca/api/v2/catalog/d...,City of Vancouver,Downtown,Lawn along Georgia Street,"{""type"": ""Point"", ""coordinates"": [-123.133965,...",Downtown,An abstract sculpture of stainless steel with ...,103,"SITE Photography, 2016",1986,NaN
1,41,NaN,Mural,In place,Main Post Office,349 West Georgia Street,ceramic,https://covapp.vancouver.ca/PublicArtRegistry/...,https://opendata.vancouver.ca/api/v2/catalog/d...,Privately owned,Downtown,lobby,"{""type"": ""Point"", ""coordinates"": [-123.114442,...",Downtown,This tile mural of a woman and child by Paul H...,76,Maxime Cyr-Morton,1958,NaN
2,43,NaN,Fountain or water feature,Removed,Vancouver Art Gallery,750 Hornby Street,"Bronze, ceramic tile",https://covapp.vancouver.ca/PublicArtRegistry/...,https://opendata.vancouver.ca/api/v2/catalog/d...,Province of British Columbia,Downtown,Front plaza,"{""type"": ""Point"", ""coordinates"": [-123.120461,...",Downtown,The fountain was commissioned by the BC Govern...,128;231,NaN,1966,NaN
3,48,NaN,Relief,In place,Block Bldg.,2695 Granville Street,"Copper, glass",https://covapp.vancouver.ca/PublicArtRegistry/...,https://opendata.vancouver.ca/api/v2/catalog/d...,private,Fairview,"Exterior, front entrance","{""type"": ""Point"", ""coordinates"": [-123.138913,...",Fairview,The copper bas-relief with abstract design and...,144;145,NaN,1965,NaN
4,63,NaN,Sculpture,In place,Victory Square,Hastings & Cambie Street,Aluminum,https://covapp.vancouver.ca/PublicArtRegistry/...,https://opendata.vancouver.ca/api/v2/catalog/d...,City of Vancouver,Downtown,South end of park,"{""type"": ""Point"", ""coordinates"": [-123.109894,...",Downtown,NaN,41,NaN,1967,NaN

In [8]:
df_right = pd.read_csv('datasets/cultural-spaces.csv', delimiter=';')
df_right.head()

,YEAR,CULTURAL_SPACE_NAME,WEBSITE,TYPE,PRIMARY_USE,ADDRESS,LOCAL_AREA,OWNERSHIP,SQUARE_FEET,NUMBER_OF_SEATS,ACTIVE_SPACE,Geom
0,2017,15th Field Artillery Regiment Museum and Archives,www.memorybc.ca/museum-of-15th-field-artillery...,Museum/Gallery,Museum/Gallery,"2025 W 11th Av, Vancouver, BC, V6J 2C7",Kitsilano,Privately Owned,NaN,NaN,Yes,"{""type"": ""Point"", ""coordinates"": [-123.151123,..."
1,2017,221A Artist Run Centre,www.221a.ca/,Museum/Gallery,Museum/Gallery,"221 E Georgia St, Vancouver, BC, V6A 1Z6",Strathcona,Privately Owned,9000.0,NaN,Yes,"{""type"": ""Point"", ""coordinates"": [-123.098796,..."
2,2017,Acme Studios,https://www.facebook.com/ACMEstudiobuilding,Studio/Rehearsal,Artist Studio,"112 E Hastings St, Vancouver, BC, V6A 4J1",Downtown,Privately Owned,18000.0,NaN,Yes,"{""type"": ""Point"", ""coordinates"": [-123.101791,..."
3,2017,AHVA Gallery,http://gallery.ahva.ubc.ca/about/,Museum/Gallery,Museum/Gallery,"6398 University Blvd, Vancouver, BC,",UBC,Other,1990.0,NaN,Yes,"{""type"": ""Point"", ""coordinates"": [-123.2549451..."
4,2017,Al Mozaico Flamenco Dance Academy,http://www.mozaicoflamenco.com/,Educational,Educational Institution,"828 E Hastings St, Vancouver, BC, V6A 1R6",Strathcona,Privately Owned,NaN,NaN,Yes,"{""type"": ""Point"", ""coordinates"": [-123.0864434..."

In [9]:
semantic_types = ['ID','Statement','Type','Status','SiteName','SiteAddress','PrimaryMaterial','URL','Ownership','LocalArea','LocationOnSite',
                  'Coordinates','Description','Quantity','Author','Year','TypeExposition','AreaSize','SiteSize','NumberOfSeats','SiteActive']

In [10]:
df_left.columns

Index(['RegistryID', 'ArtistProjectStatement', 'Type', 'Status', 'SiteName',
       'SiteAddress', 'PrimaryMaterial', 'URL', 'PhotoURL', 'Ownership',
       'Neighbourhood', 'LocationOnsite', 'Geom', 'GeoLocalArea',
       'DescriptionOfwork', 'Artists', 'PhotoCredits', 'YearOfInstallation',
       'Unnamed: 18'],
      dtype='object')

In [11]:
df_left.iloc[:5,:]

,RegistryID,ArtistProjectStatement,Type,Status,SiteName,SiteAddress,PrimaryMaterial,URL,PhotoURL,Ownership,Neighbourhood,LocationOnsite,Geom,GeoLocalArea,DescriptionOfwork,Artists,PhotoCredits,YearOfInstallation,Unnamed: 18
0,27,"""McHaffie says she means to show movement, but...",Sculpture,In place,Devonian Harbour Park,Denman & Georgia Street,"Stainless steel, cedar",https://covapp.vancouver.ca/PublicArtRegistry/...,https://opendata.vancouver.ca/api/v2/catalog/d...,City of Vancouver,Downtown,Lawn along Georgia Street,"{""type"": ""Point"", ""coordinates"": [-123.133965,...",Downtown,An abstract sculpture of stainless steel with ...,103,"SITE Photography, 2016",1986,NaN
1,41,NaN,Mural,In place,Main Post Office,349 West Georgia Street,ceramic,https://covapp.vancouver.ca/PublicArtRegistry/...,https://opendata.vancouver.ca/api/v2/catalog/d...,Privately owned,Downtown,lobby,"{""type"": ""Point"", ""coordinates"": [-123.114442,...",Downtown,This tile mural of a woman and child by Paul H...,76,Maxime Cyr-Morton,1958,NaN
2,43,NaN,Fountain or water feature,Removed,Vancouver Art Gallery,750 Hornby Street,"Bronze, ceramic tile",https://covapp.vancouver.ca/PublicArtRegistry/...,https://opendata.vancouver.ca/api/v2/catalog/d...,Province of British Columbia,Downtown,Front plaza,"{""type"": ""Point"", ""coordinates"": [-123.120461,...",Downtown,The fountain was commissioned by the BC Govern...,128;231,NaN,1966,NaN
3,48,NaN,Relief,In place,Block Bldg.,2695 Granville Street,"Copper, glass",https://covapp.vancouver.ca/PublicArtRegistry/...,https://opendata.vancouver.ca/api/v2/catalog/d...,private,Fairview,"Exterior, front entrance","{""type"": ""Point"", ""coordinates"": [-123.138913,...",Fairview,The copper bas-relief with abstract design and...,144;145,NaN,1965,NaN
4,63,NaN,Sculpture,In place,Victory Square,Hastings & Cambie Street,Aluminum,https://covapp.vancouver.ca/PublicArtRegistry/...,https://opendata.vancouver.ca/api/v2/catalog/d...,City of Vancouver,Downtown,South end of park,"{""type"": ""Point"", ""coordinates"": [-123.109894,...",Downtown,NaN,41,NaN,1967,NaN

In [12]:
from utils import (generate_prompt, 
                   generate_test_prompt, 
                    find_all_linear_names, 
                    predict, 
                    evaluate, 
                    load_pretrained_model, 
                    generate_train_val_data,
                    initiate_trainer,
                    initiate_base_model)

In [13]:
base_model_name = "meta-llama/Meta-Llama-3.1-8B"
model, tokenizer = initiate_base_model(base_model_name)

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [14]:
modules = find_all_linear_names(model)

In [135]:
#np.save('cta_types.npy',semantic_types)
semantic_types = np.load('cta_types.npy', allow_pickle=True)

def correcting_semantic_type(semantic_type):
    return semantic_type.replace(',',';')

semantic_types = np.unique(np.array(list(map(correcting_semantic_type,semantic_types))))

In [137]:
semantic_types

array(['Action', 'AdministrativeArea; GeoShape; Place', 'AggregateRating',
       'Book/name', 'BookFormatType', 'Boolean', 'Boolean; Text',
       'Boolean; URL', 'Brand', 'CategoryCode', 'ContactPoint',
       'CoordinateAT', 'Country', 'CreativeWork', 'CreativeWork/name',
       'CreativeWork; ItemList', 'CreativeWork; URL',
       'CreativeWorkSeason', 'CreativeWorkSeries', 'Date',
       'Date; DateTime', 'Date; DateTime; Time', 'DateTime; Time',
       'DayOfWeek', 'DeliveryMethod', 'Distance', 'Duration',
       'EducationalOccupationalCredential',
       'EducationalOrganization; Organization', 'Energy', 'Event/name',
       'EventAttendanceModeEnumeration', 'EventStatusType', 'GenderType',
       'GeoCoordinates; GeoShape', 'GeoShape; Place', 'Hotel/name',
       'IdentifierAT', 'Integer', 'Integer; Text', 'InteractionCounter',
       'ItemAvailability', 'ItemList; MusicRecording', 'JobPosting/name',
       'Language', 'LoanOrCredit; PaymentMethod', 'LocalBusiness/name',
       'LocationFeatureSpecification', 'Map; URL', 'Mass', 'Menu; URL',
       'MonetaryAmount', 'Movie/name', 'Museum/name', 'MusicAlbum',
       'MusicAlbum/name', 'MusicGroup; Person', 'MusicRecording/name',
       'Number', 'Number; Text', 'NutritionInformation',
       'OccupationalExperienceRequirements', 'Offer',
       'OfferItemCondition', 'OpeningHoursSpecification', 'Organization',
       'Organization; Person', 'Organization; ProgramMembership',
       'Person', 'Person/name', 'Photograph', 'Place', 'Place/name',
       'PostalAddress', 'PriceSpecification', 'Product/name',
       'Product; URL', 'ProductModel', 'PublicationEvent',
       'QuantitativeValue', 'Rating', 'Recipe/name', 'Restaurant/name',
       'RestrictedDiet', 'Review', 'SportsEvent/name', 'SportsTeam',
       'TVEpisode/name', 'Text', 'Text; URL', 'Thing', 'Time', 'URL',
       'VideoObject', 'WarrantyPromise', 'addressLocality',
       'addressRegion', 'audience', 'category', 'currency', 'email',
       'faxNumber', 'identifierNameAP', 'openingHours', 'paymentAccepted',
       'postalCode', 'price', 'priceRange', 'streetAddress', 'telephone',
       'typicalAgeRange', 'unitCode', 'unitText', 'weight', 'workHours'],
      dtype='<U37')

In [138]:
def generate_test_prompt_NextiaJD(data_point):
    cta_types = np.load('cta_types.npy', allow_pickle=True)
    return f"""
            Answer the question based on the task and instructions below. If the question cannot be answered using the information provided answer with "I don't know".
            Task: Classify the text given to you with only one of these classes that are separated with comma: {", ".join(cta_types[1:])}.
            Instructions: 1. Look at the input given to you. 2. Look at the cell values in detail.
            Column: {data_point[:50].values}
label: """.strip()

In [139]:
df_right.WEBSITE.iloc[:50].values

array(['www.memorybc.ca/museum-of-15th-field-artillery-regiment',
       'www.221a.ca/', 'https://www.facebook.com/ACMEstudiobuilding',
       'http://gallery.ahva.ubc.ca/about/',
       'http://www.mozaicoflamenco.com/', 'http://www.anzaclub.org',
       'www.artbeatus.com', 'http://www.artsfactorysociety.ca/',
       'www.artspeak.ca/', 'http://www.burrardarts.org/about.html',
       'www.britanniacentre.org',
       'http://www.musiccentre.ca/regions/british-columbia?field_event_region_value_many_to_one=3',
       'http://www.cbc.ca/bc/communityspaces/studio700.html#igImgId_11630',
       'www.lecentreculturel.com', 'http://www.christiannehayward.com/',
       'https://vancouver.ca/people-programs/artist-live-work-studio-program.aspx',
       'https://vancouver.ca/people-programs/artist-live-work-studio-program.aspx',
       'https://vancouver.ca/people-programs/artist-live-work-studio-program.aspx',
       'http://vancouver.ca/parks-recreation-culture/coal-harbour-community-centre.aspx',
       'www.chf.bc.ca', 'www.croatiancentre.com',
       'https://vancouver.ca/parks-recreation-culture/douglas-park-community-centre.aspx',
       'www.douglasreynoldsgallery.com',
       'http://dunbarcentre.org/dunbar/', 'http://cristallgallery.com',
       'http://vancouverfanclub.ca/', 'www.forgeandform.com',
       'http://gallery295.com/295/',
       'http://www.bcpotters.com/Gallery/index.php',
       'http://gordonhouse.org/', 'www.granvillefineart.com', nan,
       'www.harrisongalleries.com',
       'http://www.ams.ubc.ca/nest/arts-and-attractions/art-gallery/',
       'www.hrc.rcav.org', 'www.iantangallery.com', 'www.inuit.com',
       'www.kafkascoffee.ca', 'http://karenflamenco.com',
       'https://en.wikipedia.org/wiki/Larwill_Park',
       'http://makeisawesome.com/', 'www.makerlabs.ca',
       'http://www.marpoleoakridge.org/',
       'www.normanrothsteintheatre.com', nan,
       'http://vancouver.caparks-recreation-culture/rent-the-orpheum-annex.aspx',
       'http://www.peretz-centre.org/index.html',
       'www.pl1422.blogspot.com',
       'http://vancouver.ca/parks-recreation-culture/queen-elizabeth-park.aspx',
       'www.roeddehouse.org'], dtype=object)

In [178]:
def generate_test_prompt_NextiaJD_few_shot(data_point):
    cta_types = np.load('cta_types.npy', allow_pickle=True)
    return f"""
            Answer the question based on the task, instructions and examples below. If the question cannot be answered using the information provided answer with "I don't know".
            Task: Classify the text given to you with only one of these classes that are separated with comma: {", ".join(cta_types)}.
            Instructions: 1. Look at the input given to you. 2. Look at the cell values in detail.
            Example 1: Column: [2017, 2016, 2018, 2022, 2005, 2017, 2000, 2017, 2017]
            label: Year
            Example 2: Column: ['www.memorybc.ca/museum-of-15th-field-artillery-regiment','www.221a.ca/', 'https://www.facebook.com/ACMEstudiobuilding','http://gallery.ahva.ubc.ca/about/','http://www.mozaicoflamenco.com/', 'http://www.anzaclub.org','www.artbeatus.com', 'http://www.artsfactorysociety.ca/']
            label: URL
            Column: {data_point[:50].values}
label: """.strip()

In [179]:
X_test = pd.DataFrame(df_left.iloc[:10].apply(generate_test_prompt_NextiaJD_few_shot, axis=0), columns=["prediction"])

In [180]:
X_test

                                                               prediction
RegistryID              Answer the question based on the task, instruc...
ArtistProjectStatement  Answer the question based on the task, instruc...
Type                    Answer the question based on the task, instruc...
Status                  Answer the question based on the task, instruc...
SiteName                Answer the question based on the task, instruc...
SiteAddress             Answer the question based on the task, instruc...
PrimaryMaterial         Answer the question based on the task, instruc...
URL                     Answer the question based on the task, instruc...
PhotoURL                Answer the question based on the task, instruc...
Ownership               Answer the question based on the task, instruc...
Neighbourhood           Answer the question based on the task, instruc...
LocationOnsite          Answer the question based on the task, instruc...
Geom                    Answer the question based on the task, instruc...
GeoLocalArea            Answer the question based on the task, instruc...
DescriptionOfwork       Answer the question based on the task, instruc...
Artists                 Answer the question based on the task, instruc...
PhotoCredits            Answer the question based on the task, instruc...
YearOfInstallation      Answer the question based on the task, instruc...
Unnamed: 18             Answer the question based on the task, instruc...

In [181]:
X_test.iloc[0,:].prediction

'Answer the question based on the task, instructions and examples below. If the question cannot be answered using the information provided answer with "I don\'t know".\n            Task: Classify the text given to you with only one of these classes that are separated with comma: Product/name, Offer, currency, price, ItemAvailability, Date, OfferItemCondition, Text, IdentifierAT, category, Date, DateTime, QuantitativeValue, DeliveryMethod, WarrantyPromise, LoanOrCredit, PaymentMethod, Date, DateTime, Time, GeoShape, Place, PriceSpecification, URL, Brand, AggregateRating, Number, Text, Integer, Thing, Review, Organization, ProductModel, weight, unitCode, unitText, Distance, Product, URL, audience, Event/name, Place, PostalAddress, telephone, addressLocality, streetAddress, Map, URL, addressRegion, Organization, Person, email, EventStatusType, EventAttendanceModeEnumeration, Duration, typicalAgeRange, DateTime, Time, Language, Boolean, Recipe/name, CreativeWork, ItemList, Text, URL, NutritionInformation, Energy, Mass, CreativeWork, URL, Time, VideoObject, RestrictedDiet, InteractionCounter, Action, Person/name, postalCode, Country, faxNumber, GenderType, ContactPoint, Organization, ProgramMembership, EducationalOrganization, Organization, LocalBusiness/name, GeoCoordinates, GeoShape, CoordinateAT, priceRange, openingHours, OpeningHoursSpecification, DayOfWeek, Person, Photograph, AdministrativeArea, GeoShape, Place, paymentAccepted, MonetaryAmount, identifierNameAP, CategoryCode, EducationalOccupationalCredential, OccupationalExperienceRequirements, workHours, JobPosting/name, CreativeWork/name, Number, Restaurant/name, Boolean, URL, Menu, URL, Place/name, LocationFeatureSpecification, Movie/name, Rating, PublicationEvent, MusicGroup, Person, Book/name, BookFormatType, CreativeWork, MusicRecording/name, MusicAlbum, Hotel/name, Boolean, Text, SportsEvent/name, SportsTeam, MusicAlbum/name, ItemList, MusicRecording, TVEpisode/name, CreativeWorkSeries, Integer, Text, CreativeWorkSeason, Museum/name.\n            Instructions: 1. Look at the input given to you. 2. Look at the cell values in detail.\n            Example 1: Column: [2017, 2016, 2018, 2022, 2005, 2017, 2000, 2017, 2017]\n            label: Year\n            Example 2: Column: [\'www.memorybc.ca/museum-of-15th-field-artillery-regiment\',\'www.221a.ca/\', \'https://www.facebook.com/ACMEstudiobuilding\',\'http://gallery.ahva.ubc.ca/about/\',\'http://www.mozaicoflamenco.com/\', \'http://www.anzaclub.org\',\'www.artbeatus.com\', \'http://www.artsfactorysociety.ca/\']\n            label: URL\n            Column: [ 27  41  43  48  63  69  77  89  90 100]\nlabel:'

In [182]:
X_test.iloc[1,:].prediction

'Answer the question based on the task, instructions and examples below. If the question cannot be answered using the information provided answer with "I don\'t know".\n            Task: Classify the text given to you with only one of these classes that are separated with comma: Product/name, Offer, currency, price, ItemAvailability, Date, OfferItemCondition, Text, IdentifierAT, category, Date, DateTime, QuantitativeValue, DeliveryMethod, WarrantyPromise, LoanOrCredit, PaymentMethod, Date, DateTime, Time, GeoShape, Place, PriceSpecification, URL, Brand, AggregateRating, Number, Text, Integer, Thing, Review, Organization, ProductModel, weight, unitCode, unitText, Distance, Product, URL, audience, Event/name, Place, PostalAddress, telephone, addressLocality, streetAddress, Map, URL, addressRegion, Organization, Person, email, EventStatusType, EventAttendanceModeEnumeration, Duration, typicalAgeRange, DateTime, Time, Language, Boolean, Recipe/name, CreativeWork, ItemList, Text, URL, NutritionInformation, Energy, Mass, CreativeWork, URL, Time, VideoObject, RestrictedDiet, InteractionCounter, Action, Person/name, postalCode, Country, faxNumber, GenderType, ContactPoint, Organization, ProgramMembership, EducationalOrganization, Organization, LocalBusiness/name, GeoCoordinates, GeoShape, CoordinateAT, priceRange, openingHours, OpeningHoursSpecification, DayOfWeek, Person, Photograph, AdministrativeArea, GeoShape, Place, paymentAccepted, MonetaryAmount, identifierNameAP, CategoryCode, EducationalOccupationalCredential, OccupationalExperienceRequirements, workHours, JobPosting/name, CreativeWork/name, Number, Restaurant/name, Boolean, URL, Menu, URL, Place/name, LocationFeatureSpecification, Movie/name, Rating, PublicationEvent, MusicGroup, Person, Book/name, BookFormatType, CreativeWork, MusicRecording/name, MusicAlbum, Hotel/name, Boolean, Text, SportsEvent/name, SportsTeam, MusicAlbum/name, ItemList, MusicRecording, TVEpisode/name, CreativeWorkSeries, Integer, Text, CreativeWorkSeason, Museum/name.\n            Instructions: 1. Look at the input given to you. 2. Look at the cell values in detail.\n            Example 1: Column: [2017, 2016, 2018, 2022, 2005, 2017, 2000, 2017, 2017]\n            label: Year\n            Example 2: Column: [\'www.memorybc.ca/museum-of-15th-field-artillery-regiment\',\'www.221a.ca/\', \'https://www.facebook.com/ACMEstudiobuilding\',\'http://gallery.ahva.ubc.ca/about/\',\'http://www.mozaicoflamenco.com/\', \'http://www.anzaclub.org\',\'www.artbeatus.com\', \'http://www.artsfactorysociety.ca/\']\n            label: URL\n            Column: [\'"McHaffie says she means to show movement, but not flight. \\\'My perception of the world is that very little of it is stable,\\\' she says." -Vancouver Sun, July 19,1986                                             The sculpture was installed as one of ten pieces in the City Shapes sculpture symposium in the City\\\'s centennial year.\'\n nan nan nan nan nan nan\n "In 1914 two posts were rented from Chief Tsa-wee-nok of Kingcome Inlet as part of the movie set for In the Land of the Head Hunters by Edward Curtis. The Art, Historical and Scientific Association of Vancouver bought them in 1927 for Stanley Park. When the first one decayed badly it was replaced by a fibreglas pole (situated near the miniature railway). The original was restored by James\'s granddaughter Ellen Neel in 1963 and is stored at the Vancouver Museum. In 1988 Tony Hunt carved a replica to replace the second one which is at Brockton Point.- from Hillary Stewart, Totem Poles, 1990, Douglas &amp; McIntyre"\n nan\n \'This pole was erected to commemorate the meeting of the Squamish people and Captain George Vancouver near the mouth of the Capilano River in June 1792. According to Terri Clark at the Parks office in 2006, "..pole was taken down due to rot over 18 years ago and stored in SP yard where it was subsequently consumed by a shed fire - its ashes have returned to the soil."\']\nlabel:'

In [183]:
X_test.iloc[10,:].prediction

'Answer the question based on the task, instructions and examples below. If the question cannot be answered using the information provided answer with "I don\'t know".\n            Task: Classify the text given to you with only one of these classes that are separated with comma: Product/name, Offer, currency, price, ItemAvailability, Date, OfferItemCondition, Text, IdentifierAT, category, Date, DateTime, QuantitativeValue, DeliveryMethod, WarrantyPromise, LoanOrCredit, PaymentMethod, Date, DateTime, Time, GeoShape, Place, PriceSpecification, URL, Brand, AggregateRating, Number, Text, Integer, Thing, Review, Organization, ProductModel, weight, unitCode, unitText, Distance, Product, URL, audience, Event/name, Place, PostalAddress, telephone, addressLocality, streetAddress, Map, URL, addressRegion, Organization, Person, email, EventStatusType, EventAttendanceModeEnumeration, Duration, typicalAgeRange, DateTime, Time, Language, Boolean, Recipe/name, CreativeWork, ItemList, Text, URL, NutritionInformation, Energy, Mass, CreativeWork, URL, Time, VideoObject, RestrictedDiet, InteractionCounter, Action, Person/name, postalCode, Country, faxNumber, GenderType, ContactPoint, Organization, ProgramMembership, EducationalOrganization, Organization, LocalBusiness/name, GeoCoordinates, GeoShape, CoordinateAT, priceRange, openingHours, OpeningHoursSpecification, DayOfWeek, Person, Photograph, AdministrativeArea, GeoShape, Place, paymentAccepted, MonetaryAmount, identifierNameAP, CategoryCode, EducationalOccupationalCredential, OccupationalExperienceRequirements, workHours, JobPosting/name, CreativeWork/name, Number, Restaurant/name, Boolean, URL, Menu, URL, Place/name, LocationFeatureSpecification, Movie/name, Rating, PublicationEvent, MusicGroup, Person, Book/name, BookFormatType, CreativeWork, MusicRecording/name, MusicAlbum, Hotel/name, Boolean, Text, SportsEvent/name, SportsTeam, MusicAlbum/name, ItemList, MusicRecording, TVEpisode/name, CreativeWorkSeries, Integer, Text, CreativeWorkSeason, Museum/name.\n            Instructions: 1. Look at the input given to you. 2. Look at the cell values in detail.\n            Example 1: Column: [2017, 2016, 2018, 2022, 2005, 2017, 2000, 2017, 2017]\n            label: Year\n            Example 2: Column: [\'www.memorybc.ca/museum-of-15th-field-artillery-regiment\',\'www.221a.ca/\', \'https://www.facebook.com/ACMEstudiobuilding\',\'http://gallery.ahva.ubc.ca/about/\',\'http://www.mozaicoflamenco.com/\', \'http://www.anzaclub.org\',\'www.artbeatus.com\', \'http://www.artsfactorysociety.ca/\']\n            label: URL\n            Column: [\'Downtown\' \'Downtown\' \'Downtown\' \'Fairview\' \'Downtown\' \'Downtown\'\n \'Downtown\' \'Stanley Park\' \'Downtown\' nan]\nlabel:'

In [184]:
X_test.iloc[13,:].prediction

'Answer the question based on the task, instructions and examples below. If the question cannot be answered using the information provided answer with "I don\'t know".\n            Task: Classify the text given to you with only one of these classes that are separated with comma: Product/name, Offer, currency, price, ItemAvailability, Date, OfferItemCondition, Text, IdentifierAT, category, Date, DateTime, QuantitativeValue, DeliveryMethod, WarrantyPromise, LoanOrCredit, PaymentMethod, Date, DateTime, Time, GeoShape, Place, PriceSpecification, URL, Brand, AggregateRating, Number, Text, Integer, Thing, Review, Organization, ProductModel, weight, unitCode, unitText, Distance, Product, URL, audience, Event/name, Place, PostalAddress, telephone, addressLocality, streetAddress, Map, URL, addressRegion, Organization, Person, email, EventStatusType, EventAttendanceModeEnumeration, Duration, typicalAgeRange, DateTime, Time, Language, Boolean, Recipe/name, CreativeWork, ItemList, Text, URL, NutritionInformation, Energy, Mass, CreativeWork, URL, Time, VideoObject, RestrictedDiet, InteractionCounter, Action, Person/name, postalCode, Country, faxNumber, GenderType, ContactPoint, Organization, ProgramMembership, EducationalOrganization, Organization, LocalBusiness/name, GeoCoordinates, GeoShape, CoordinateAT, priceRange, openingHours, OpeningHoursSpecification, DayOfWeek, Person, Photograph, AdministrativeArea, GeoShape, Place, paymentAccepted, MonetaryAmount, identifierNameAP, CategoryCode, EducationalOccupationalCredential, OccupationalExperienceRequirements, workHours, JobPosting/name, CreativeWork/name, Number, Restaurant/name, Boolean, URL, Menu, URL, Place/name, LocationFeatureSpecification, Movie/name, Rating, PublicationEvent, MusicGroup, Person, Book/name, BookFormatType, CreativeWork, MusicRecording/name, MusicAlbum, Hotel/name, Boolean, Text, SportsEvent/name, SportsTeam, MusicAlbum/name, ItemList, MusicRecording, TVEpisode/name, CreativeWorkSeries, Integer, Text, CreativeWorkSeason, Museum/name.\n            Instructions: 1. Look at the input given to you. 2. Look at the cell values in detail.\n            Example 1: Column: [2017, 2016, 2018, 2022, 2005, 2017, 2000, 2017, 2017]\n            label: Year\n            Example 2: Column: [\'www.memorybc.ca/museum-of-15th-field-artillery-regiment\',\'www.221a.ca/\', \'https://www.facebook.com/ACMEstudiobuilding\',\'http://gallery.ahva.ubc.ca/about/\',\'http://www.mozaicoflamenco.com/\', \'http://www.anzaclub.org\',\'www.artbeatus.com\', \'http://www.artsfactorysociety.ca/\']\n            label: URL\n            Column: [\'Downtown\' \'Downtown\' \'Downtown\' \'Fairview\' \'Downtown\' \'Downtown\'\n \'Downtown\' nan \'Downtown\' nan]\nlabel:'

In [185]:
y_pred = predict(X_test, model, tokenizer)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:06<00:00,  3.05it/s]

In [186]:
y_pred

['Integer',
 'Text',
 'Text',
 'ItemAvailability',
 'Text',
 'Place',
 'Text',
 'URL',
 'URL',
 'Text',
 'addressLoc',
 'Text',
 'GeoShape',
 'addressLoc',
 'Text',
 'IdentifierAT',
 'Text',
 'none',
 'Text']

In [187]:
predictions_left = pd.DataFrame({
                            "Column":df_left.columns, 
                            "Predicted":y_pred
                            })
predictions_left

                    Column         Predicted
0               RegistryID           Integer
1   ArtistProjectStatement              Text
2                     Type              Text
3                   Status  ItemAvailability
4                 SiteName              Text
5              SiteAddress             Place
6          PrimaryMaterial              Text
7                      URL               URL
8                 PhotoURL               URL
9                Ownership              Text
10           Neighbourhood        addressLoc
11          LocationOnsite              Text
12                    Geom          GeoShape
13            GeoLocalArea        addressLoc
14       DescriptionOfwork              Text
15                 Artists      IdentifierAT
16            PhotoCredits              Text
17      YearOfInstallation              none
18             Unnamed: 18              Text

In [188]:
y_pred[10]

'addressLoc'

In [189]:
y_pred[13]

'addressLoc'

In [190]:
X_test = pd.DataFrame(df_right.iloc[:10].apply(generate_test_prompt_NextiaJD_few_shot, axis=0), columns=["prediction"])
y_pred = predict(X_test, model, tokenizer)
predictions_right = pd.DataFrame({
                            "Column":df_right.columns, 
                            "Predicted":y_pred
                            })
predictions_right

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.13it/s]

                 Column         Predicted
0                  YEAR              none
1   CULTURAL_SPACE_NAME              Text
2               WEBSITE               URL
3                  TYPE          Category
4           PRIMARY_USE              Text
5               ADDRESS           address
6            LOCAL_AREA        addressLoc
7             OWNERSHIP  ItemAvailability
8           SQUARE_FEET             Price
9       NUMBER_OF_SEATS             Price
10         ACTIVE_SPACE              Text
11                 Geom          GeoShape

In [191]:
predicted_joinable_columns = []

for i in range(predictions_left.shape[0]):
    column = predictions_left.iloc[i,0]
    predicted_semantic_type = predictions_left.iloc[i,1]
    for j in range(predictions_right.shape[0]):
        if(predicted_semantic_type == predictions_right.iloc[j,1]):
            predicted_joinable_columns.append([column, predictions_right.iloc[j,:].Column, predicted_semantic_type])

In [192]:
sameSTColumns = pd.DataFrame(np.array(predicted_joinable_columns), columns=['ColumnLeft','ColumnRight','SemanticType'])
sameSTColumns

                ColumnLeft          ColumnRight      SemanticType
0   ArtistProjectStatement  CULTURAL_SPACE_NAME              Text
1   ArtistProjectStatement          PRIMARY_USE              Text
2   ArtistProjectStatement         ACTIVE_SPACE              Text
3                     Type  CULTURAL_SPACE_NAME              Text
4                     Type          PRIMARY_USE              Text
5                     Type         ACTIVE_SPACE              Text
6                   Status            OWNERSHIP  ItemAvailability
7                 SiteName  CULTURAL_SPACE_NAME              Text
8                 SiteName          PRIMARY_USE              Text
9                 SiteName         ACTIVE_SPACE              Text
10         PrimaryMaterial  CULTURAL_SPACE_NAME              Text
11         PrimaryMaterial          PRIMARY_USE              Text
12         PrimaryMaterial         ACTIVE_SPACE              Text
13                     URL              WEBSITE               URL
14                PhotoURL              WEBSITE               URL
15               Ownership  CULTURAL_SPACE_NAME              Text
16               Ownership          PRIMARY_USE              Text
17               Ownership         ACTIVE_SPACE              Text
18           Neighbourhood           LOCAL_AREA        addressLoc
19          LocationOnsite  CULTURAL_SPACE_NAME              Text
20          LocationOnsite          PRIMARY_USE              Text
21          LocationOnsite         ACTIVE_SPACE              Text
22                    Geom                 Geom          GeoShape
23            GeoLocalArea           LOCAL_AREA        addressLoc
24       DescriptionOfwork  CULTURAL_SPACE_NAME              Text
25       DescriptionOfwork          PRIMARY_USE              Text
26       DescriptionOfwork         ACTIVE_SPACE              Text
27            PhotoCredits  CULTURAL_SPACE_NAME              Text
28            PhotoCredits          PRIMARY_USE              Text
29            PhotoCredits         ACTIVE_SPACE              Text
30      YearOfInstallation                 YEAR              none
31             Unnamed: 18  CULTURAL_SPACE_NAME              Text
32             Unnamed: 18          PRIMARY_USE              Text
33             Unnamed: 18         ACTIVE_SPACE              Text

In [193]:
def jaccard_similarity(set1, set2):
    
    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))
     
    return intersection / union

In [194]:
similarity = []
for i in range(sameSTColumns.shape[0]):
    try:
        similarity.append(jaccard_similarity(set(df_left[sameSTColumns.iloc[i,0]].unique()), set(df_right[sameSTColumns.iloc[i,1]].unique())))
    except:
        similarity.append(jaccard_similarity(set(df_right[sameSTColumns.iloc[i,0]].unique()), set(df_left[sameSTColumns.iloc[i,1]].unique())))
similarity

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.027906976744186046,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.001088139281828074,
 0.0019047619047619048,
 0.0,
 0.0,
 0.8148148148148148,
 0.0011086474501108647,
 0.0,
 0.0,
 0.0,
 0.8,
 0.0,
 0.0,
 0.0,
 0.0016181229773462784,
 0.0,
 0.0,
 0.05,
 0.0,
 0.0,
 0.0]

In [195]:
sameSTColumns['JaccardSimilarity'] = similarity
sameSTColumns

,ColumnLeft,ColumnRight,SemanticType,JaccardSimilarity
0,ArtistProjectStatement,CULTURAL_SPACE_NAME,Text,0.000000
1,ArtistProjectStatement,PRIMARY_USE,Text,0.000000
2,ArtistProjectStatement,ACTIVE_SPACE,Text,0.000000
3,Type,CULTURAL_SPACE_NAME,Text,0.000000
4,Type,PRIMARY_USE,Text,0.000000
5,Type,ACTIVE_SPACE,Text,0.000000
6,Status,OWNERSHIP,ItemAvailability,0.000000
7,SiteName,CULTURAL_SPACE_NAME,Text,0.027907
8,SiteName,PRIMARY_USE,Text,0.000000
9,SiteName,ACTIVE_SPACE,Text,0.000000
10,PrimaryMaterial,CULTURAL_SPACE_NAME,Text,0.000000
11,PrimaryMaterial,PRIMARY_USE,Text,0.000000
12,PrimaryMaterial,ACTIVE_SPACE,Text,0.000000
13,URL,WEBSITE,URL,0.000000
14,PhotoURL,WEBSITE,URL,0.001088
15,Ownership,CULTURAL_SPACE_NAME,Text,0.001905
16,Ownership,PRIMARY_USE,Text,0.000000
17,Ownership,ACTIVE_SPACE,Text,0.000000
18,Neighbourhood,LOCAL_AREA,addressLoc,0.814815
19,LocationOnsite,CULTURAL_SPACE_NAME,Text,0.001109
20,LocationOnsite,PRIMARY_USE,Text,0.000000
21,LocationOnsite,ACTIVE_SPACE,Text,0.000000
22,Geom,Geom,GeoShape,0.000000
23,GeoLocalArea,LOCAL_AREA,addressLoc,0.800000
24,DescriptionOfwork,CULTURAL_SPACE_NAME,Text,0.000000
25,DescriptionOfwork,PRIMARY_USE,Text,0.000000
26,DescriptionOfwork,ACTIVE_SPACE,Text,0.000000
27,PhotoCredits,CULTURAL_SPACE_NAME,Text,0.001618
28,PhotoCredits,PRIMARY_USE,Text,0.000000
29,PhotoCredits,ACTIVE_SPACE,Text,0.000000
30,YearOfInstallation,YEAR,none,0.050000
31,Unnamed: 18,CULTURAL_SPACE_NAME,Text,0.000000
32,Unnamed: 18,PRIMARY_USE,Text,0.000000
33,Unnamed: 18,ACTIVE_SPACE,Text,0.000000

In [196]:
joinableColumns = sameSTColumns[sameSTColumns['JaccardSimilarity'] > 0.5]
joinableColumns

       ColumnLeft ColumnRight SemanticType  JaccardSimilarity
18  Neighbourhood  LOCAL_AREA   addressLoc           0.814815
23   GeoLocalArea  LOCAL_AREA   addressLoc           0.800000